### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [edusynch/moodle-quizaccess_edusynch#2]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data - as your plugin submits data to an external service, implmenting the privacy api is a requirement for approval in the plugins db.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

Please pay careful attention to the "add_external_location_link" api - your plugin must implement this as well as the other functions required for deleting and exporting data.

**Comment by seankila** [comment]
Hey Dan,

We have a question for you - as our plugin doesn't actually have any tables on the Moodle database to store user data, we're not sure that we need to implement the majority of the functions in our privacy API build. As such, we implemented the "get_metadata" function to showcase that while we are collecting some user information with everything being sent to our API. 

Anyway, we were hoping to verify that this meets the requirements on your side, and if it doesn't would you be able to guide us as to what we need to do to meet the requirements? Is there an example of a plugin that is similar to ours that we can use as a base case to check out their Privacy API build?

**Comment by clenisson** [comment]
Hi Dan,

We've submitted our implementation of Privacy API according to Sean's comment above, to be evaluated. Can you give us a feedback about it?

https://github.com/edusynch/moodle-quizaccess_edusynch/commit/6005f793deb960e06c97c55e7264fb5b922a07b7#diff-76112e9cfbad081959021ab9520f48deaf00fbcaa69aca479f03d034fe624519

**Comment by danmarsden** [comment]
yeah that looks like what I was expecting to see - nice! :-)

**Comment by clenisson** [comment]
@danmarsden thanks! :)
