### ISSUE TITLE
hard coded lang strings

### ISSUE THREAD

**Issue by danmarsden** [edusynch/moodle-quizaccess_edusynch#7]
https://github.com/edusynch/moodle-quizaccess_edusynch/blob/master/index.php#L42
https://github.com/edusynch/moodle-quizaccess_edusynch/blob/master/index.php#L54

please review all user facing strings and ensure they are stored within the lang file for translation.

note this is a blocker for plugins db approval.

**Comment by danmarsden** [comment]
https://github.com/edusynch/moodle-quizaccess_edusynch/blob/master/setup_quiz.php#L35

**Comment by clenisson** [comment]
Hi Dan, 

Thanks for your feedback. We've submitted a new version that fixes it :)
