### ISSUE TITLE
undocumented use of CDN for loading JS

### ISSUE THREAD

**Issue by danmarsden** [edusynch/moodle-quizaccess_edusynch#9]
https://github.com/edusynch/moodle-quizaccess_edusynch/blob/master/setup_quiz.php#L40

Some organisations will implment csp policies that will block this, but Moodle also includes the jquery lib in core so it would be good for you to check if you can leverage the core JS intead of loading it from a CDN

If you want to load it from a CDN you should include information in your Readme file that covers this.

**Comment by danmarsden** [comment]
https://github.com/edusynch/moodle-quizaccess_edusynch/blob/master/views/session.php#L268-L271

**Comment by clenisson** [comment]
Hi Dan, 

Thanks for your feedback. We've submitted a new version that fixes it :)
